version: '3.1'

services:
  database:
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: root-password
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
