spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres?user=postgres&password=postgres
    username: postgres
    password: postgres
    pool-size: 30
  flyway:
    url: jdbc:postgresql://localhost/postgres
    user: postgres
    password: postgres
